### ISSUE TITLE
Motion is Emotion: Prototyping Microinteractions...

### ISSUE THREAD

**Issue by jshmllr** [podo/awesome-framer#17]
[Motion is Emotion: Prototyping Microinteractions for Apple Watch with Framer Studio - Apple Watch temperature gauge prototype tutorial.
](https://blog.grandcentrix.net/motion-is-emotion/ )

URL Dead
can point to https://web.archive.org/web/20160304015511/https://blog.grandcentrix.net/motion-is-emotion/ now and prototype at: https://github.com/gcx-engine-room/apple_watch_framer_experiments/tree/master/animated_color_change_variable_wobble.framer

**Comment by podo** [comment]
Thanks for the report! Updated the link from Web Archive.
