### ISSUE TITLE
Add Free Voyage UI kit

### ISSUE THREAD

**Issue by deadcoder0904** [podo/awesome-framer#9]
I would've sent a PR but don't know where to add the Free UI Kit [Voyage](https://framer.com/voyage/) section

**Comment by podo** [comment]
I don’t think it’s a module similar to [framer material kit](https://github.com/k-vyn/framer-material-kit), so my suggestion is to add it to [Other](https://github.com/podo/awesome-framer#other) section, until there will be more UI kits.

**Comment by deadcoder0904** [comment]
Sent a PR - #10 🎉

**Comment by deadcoder0904** [comment]
Sent a PR - #10 🎉
